# Generated by Django 4.1.3 on 2022-12-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('physical_address', models.TextField()),
                ('provider', models.CharField(max_length=255)),
                ('internet_channel_cost', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('lte_category', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('hdd', models.CharField(max_length=255)),
                ('hdd_quantity', models.CharField(max_length=255)),
                ('operation_system', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_equipment.equipmentlocation')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_system', models.CharField(max_length=255)),
                ('cores_quantity', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('ip_addresses_quantity', models.CharField(max_length=255)),
                ('ip_addresses', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_equipment.server')),
            ],
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('imai', models.CharField(max_length=255)),
                ('subscription_fee', models.CharField(max_length=255)),
                ('last_pay_date', models.DateField()),
                ('modem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_equipment.modem')),
            ],
        ),
        migrations.CreateModel(
            name='RouterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('provider_ip_address', models.CharField(max_length=255)),
                ('provider_mask', models.CharField(max_length=255)),
                ('provider_gateway', models.CharField(max_length=255)),
                ('internet_channel_speed', models.CharField(max_length=255)),
                ('internet_connection_type', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_equipment.equipmentlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Router_4G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('tunnel_ip_address', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('router_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_equipment.routerpoint')),
            ],
        ),
        migrations.AddField(
            model_name='modem',
            name='router_4g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_equipment.router_4g'),
        ),
        migrations.CreateModel(
            name='Daemon_3proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ports_quantity', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('users_quantity', models.CharField(max_length=255)),
                ('internam_ip', models.CharField(max_length=255)),
                ('external_ip', models.CharField(max_length=255)),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_equipment.virtualmachine')),
            ],
        ),
    ]
